[package]
name = "git-add"
version = "0.1.0"
edition = "2021"
authors = ["vasant hegde"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.12"
